apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: micro-shop
spec:
  selector:
    name: mysql-pod
    app: micro-shop
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
