apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
    app: micro-shop
spec:
  selector:
    name: api-pod
    app: micro-shop
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP

