apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    name: products-service
    app: micro-shop
spec:
  selector:
    name: products-pod
    app: micro-shop
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP

