apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order-service
    app: micro-shop
spec:
  selector:
    name: orders-pod
    app: micro-shop
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP

